### ISSUE TITLE
PHP Packages question

### ISSUE THREAD

**Issue by SecT0uch** [mudpi/installer#8]
Hey @olixr !
I'm about to reinstall mudpi from scratch in order to test the core's feature branch and a few question came to my mind:

First off, is it necessary to add a third-party repo to install PHP ? I'm using armbian and I can find the PHP 7.3 packages in the default repo.

Could we safely update PHP to 7.4 or 8.0 ? We can see the incompatibilities [from 7.3 to 7.4 here](https://www.php.net/manual/en/migration74.incompatible.php) and [from 7.4 to 8.0 here](https://www.php.net/manual/en/migration80.incompatible.php).
[Here is a link to see all available packages in all the distributions](https://repology.org/project/php/versions)

For now, I'm gonna use the PHP 7.3 packages, in order to test the feature branch.

As a side note, I'm gonna update the manual install to remove the unneeded dependencies and add the new ones. I'm thinking about RPi.GPIO and blinka. Once ready, I will PR in a new feature branch.

**Comment by olixr** [comment]
@SecT0uch I would prefer to go at least 7.4php actually. So I don't see an issue with that. 

I was also unaware that support was finally in the packages for that php version. I made the installer a little after the 3 had just come out and was still dealing with ARMv6 boards. 

If you can install the php7.4 or 8 and let me know if you are able to do so without the repo addition. Also let me know which pi you are using because I would ideally like to get php 7.4 running on ARMv6 (pi zero) as well.

**Comment by SecT0uch** [comment]
After a quick check on Repology, PHP 7.4 and 8.0 are only available in Raspbian Testing, however I can see PHP 7.3 in Raspbian Stable. 
I'm running Armbian on a Sopine from Pine64, and 7.3 is also in the default repo.

We should maybe stick to 7.3 for now, and remove the third party repo ? (After double-check if PHP 7.3 is available for Pi Zero)
